# Generated by Django 3.1.12 on 2022-05-09 15:26

import apps.base.models.customer
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='constancia',
            field=models.FileField(storage=apps.base.models.customer.OverwriteStorage(), upload_to='constancias/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='regimen',
            field=models.CharField(choices=[('601', 'General de Ley Personas Morales'), ('603', 'Personas Morales con Fines no Lucrativos'), ('605', 'Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', 'Arrendamiento'), ('607', 'Régimen de Enajenación o Adquisición de Bienes'), ('608', 'Demás ingresos'), ('610', 'Residentes en el Extranjero sin Establecimiento Permanente en México'), ('611', 'Ingresos por Dividendos (socios y accionistas)'), ('612', 'Personas Físicas con Actividades Empresariales y Profesionales'), ('614', 'Ingresos por intereses'), ('615', 'Régimen de los ingresos por obtención de premios'), ('616', 'Sin obligaciones fiscales'), ('620', 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', 'Incorporación Fiscal (RIF)'), ('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', 'Opcional para Grupos de Sociedades'), ('624', 'Coordinados'), ('625', 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', 'Régimen Simplificado de Confianza (RESICO)')], max_length=3),
        ),
    ]
