# Generated by Django 3.1.12 on 2022-05-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220509_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('sale_id', models.CharField(max_length=20, unique=True)),
                ('total', models.FloatField()),
                ('factura', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Emitido'), ('3', 'Enviado'), ('4', 'Cancelado')], default='1', max_length=1)),
                ('customer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
            options={
                'verbose_name': 'Meli Sale',
                'verbose_name_plural': 'Meli Sales',
            },
        ),
    ]
