# Generated by Django 3.1.12 on 2022-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('message', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'verbose_name': 'Predefined Answer',
                'verbose_name_plural': 'Predefined Answers',
            },
        ),
    ]
