# Generated by Django 3.1.12 on 2022-05-18 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('tracking', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.invoice')),
            ],
            options={
                'verbose_name': 'Tracked sale',
                'verbose_name_plural': 'Tracked Sales',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
