# Generated by Django 3.1.12 on 2022-05-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220518_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedsale',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_tracking', to='base.invoice'),
        ),
    ]
