# Generated by Django 3.1.12 on 2022-05-31 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220523_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': [django.db.models.functions.text.Upper('key')], 'verbose_name': 'Predefined Answer', 'verbose_name_plural': 'Predefined Answers'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='key',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='base.customer'),
        ),
        migrations.AlterField(
            model_name='trackedsale',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='base.invoice'),
        ),
    ]
