# Generated by Django 3.1.12 on 2022-07-06 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220531_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': [django.db.models.functions.text.Upper('name')], 'verbose_name': 'Predefined Answer', 'verbose_name_plural': 'Predefined Answers'},
        ),
        migrations.AddField(
            model_name='answer',
            name='context',
            field=models.CharField(choices=[('q', 'Question'), ('c', 'Chat'), ('a', 'All')], default='c', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='constancia',
            field=models.FileField(upload_to='constancias/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
